name: Build APK with Buildozer

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git zip unzip openjdk-17-jdk \
            python3-pip build-essential \
            libncurses5 libstdc++6 libffi-dev \
            libssl-dev libsqlite3-dev zlib1g-dev \
            libjpeg-dev libfreetype6-dev

          python3 -m pip install --upgrade pip
          python3 -m pip install --user buildozer Cython

      - name: Build APK
        run: |
          export PATH=$PATH:$HOME/.local/bin
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: cuaapp.apk
          path: bin/*.apk
